on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-init
        with:
          args: 'init "-l config"'
      - name: West Update
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-update
        with:
          args: 'update'
      - name: West Config Zephyr Base
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-config
        with:
          args: 'config "--global zephyr.base-prefer configfile"'
      - name: West Zephyr Export
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-zephyr-export
        with:
          args: 'zephyr-export'
      - name: West Build (_33BLE Bigspace)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-underscore33-bigspace
        with:
          args: 'build "-s zmk/app -b underscore33-bigspace -- -DZMK_CONFIG=/github/workspace/config/"'
      - name: _33BLE Bigspace DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/underscore33-bigspace.dts.pre.tmp
      - name: _33BLE Bigspace Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 underscore33-bigspace.uf2
      - name: Archive (_33BLE Bigspace)
        uses: actions/upload-artifact@v2
        with:
          name: bigspace
          path: underscore33-bigspace.uf2
      - name: West Build (_33BLE Splitspace)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-underscore33
        with:
          args: 'build "-s zmk/app -b underscore33 -- -DZMK_CONFIG=/github/workspace/config/"'
      - name: _33BLE Splitspace DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/underscore33.dts.pre.tmp
      - name: _33BLE Splitspace Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 underscore33-splitspace.uf2
      - name: Archive (_33BLE Splitspace)
        uses: actions/upload-artifact@v2
        with:
          name: splitspace
          path: underscore33-splitspace.uf2
